package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 * Creates the Resource Discovery tables and migrates existing DOCKERREPOSITORY
 * MonitoredResource rows into the new resource_discovery table.
 */
public class V19__add_resource_discovery_tables extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection conn = context.getConnection();
        String product = conn.getMetaData().getDatabaseProductName().toLowerCase();

        createTables(conn, product);

        if (tableExists(conn, "monitored_resource")) {
            migrateDockerRepositoryResources(conn);
        }
    }

    private void createTables(Connection conn, String product) throws Exception {
        try (Statement stmt = conn.createStatement()) {
            if (product.contains("h2")) {
                stmt.execute("""
                    CREATE TABLE IF NOT EXISTS discovery_service_config (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        type_name VARCHAR(100) UNIQUE,
                        sync_interval_minutes INT DEFAULT 60,
                        parallelism INT DEFAULT 1
                    )
                    """);
                stmt.execute("""
                    CREATE TABLE IF NOT EXISTS resource_discovery (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        type VARCHAR(50),
                        target VARCHAR(1000),
                        skip_tls BOOLEAN DEFAULT FALSE,
                        recursive_enabled BOOLEAN DEFAULT FALSE,
                        active BOOLEAN DEFAULT TRUE,
                        created_at TIMESTAMP
                    )
                    """);
                stmt.execute("""
                    CREATE TABLE IF NOT EXISTS discovery_service_auth (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        discovery_service_config_id BIGINT NOT NULL,
                        name VARCHAR(255),
                        auth_type VARCHAR(50),
                        url_pattern VARCHAR(1000),
                        username VARCHAR(255),
                        password VARCHAR(255),
                        FOREIGN KEY (discovery_service_config_id) REFERENCES discovery_service_config(id)
                    )
                    """);
            } else {
                // PostgreSQL
                stmt.execute("""
                    CREATE TABLE IF NOT EXISTS discovery_service_config (
                        id BIGSERIAL PRIMARY KEY,
                        type_name VARCHAR(100) UNIQUE,
                        sync_interval_minutes INT DEFAULT 60,
                        parallelism INT DEFAULT 1
                    )
                    """);
                stmt.execute("""
                    CREATE TABLE IF NOT EXISTS resource_discovery (
                        id BIGSERIAL PRIMARY KEY,
                        name VARCHAR(255),
                        type VARCHAR(50),
                        target VARCHAR(1000),
                        skip_tls BOOLEAN DEFAULT FALSE,
                        recursive_enabled BOOLEAN DEFAULT FALSE,
                        active BOOLEAN DEFAULT TRUE,
                        created_at TIMESTAMP
                    )
                    """);
                stmt.execute("""
                    CREATE TABLE IF NOT EXISTS discovery_service_auth (
                        id BIGSERIAL PRIMARY KEY,
                        discovery_service_config_id BIGINT NOT NULL,
                        name VARCHAR(255),
                        auth_type VARCHAR(50),
                        url_pattern VARCHAR(1000),
                        username VARCHAR(255),
                        password VARCHAR(255),
                        FOREIGN KEY (discovery_service_config_id) REFERENCES discovery_service_config(id)
                    )
                    """);
            }
        }
    }

    private void migrateDockerRepositoryResources(Connection conn) throws Exception {
        // Check if there are any DOCKERREPOSITORY rows to migrate
        boolean hasRows;
        try (var ps = conn.prepareStatement(
                "SELECT COUNT(*) FROM monitored_resource WHERE resource_type = 'DOCKERREPOSITORY'");
             ResultSet rs = ps.executeQuery()) {
            rs.next();
            hasRows = rs.getLong(1) > 0;
        }
        if (!hasRows) {
            return;
        }

        // Insert into resource_discovery
        try (Statement stmt = conn.createStatement()) {
            stmt.execute("""
                INSERT INTO resource_discovery (name, type, target, skip_tls, recursive_enabled, active, created_at)
                SELECT name, 'DOCKER_REPOSITORY', target, skip_tls, recursive_enabled, active, created_at
                FROM monitored_resource
                WHERE resource_type = 'DOCKERREPOSITORY'
                """);
        }

        // Remove join-table entries for DOCKERREPOSITORY resources
        if (tableExists(conn, "resource_group_resource")) {
            try (Statement stmt = conn.createStatement()) {
                stmt.execute("""
                    DELETE FROM resource_group_resource
                    WHERE resource_id IN (
                        SELECT id FROM monitored_resource WHERE resource_type = 'DOCKERREPOSITORY'
                    )
                    """);
            }
        }

        // Delete DOCKERREPOSITORY resources from monitored_resource
        try (Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM monitored_resource WHERE resource_type = 'DOCKERREPOSITORY'");
        }

        // Migrate auth credentials from resource_type_auth / resource_type_config
        migrateAuthCredentials(conn);
    }

    private void migrateAuthCredentials(Connection conn) throws Exception {
        if (!tableExists(conn, "resource_type_config") || !tableExists(conn, "resource_type_auth")) {
            return;
        }

        // Find DOCKERREPOSITORY config id
        Long dockerRepoConfigId = null;
        try (var ps = conn.prepareStatement(
                "SELECT id FROM resource_type_config WHERE type_name = 'DOCKERREPOSITORY'");
             ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                dockerRepoConfigId = rs.getLong(1);
            }
        }
        if (dockerRepoConfigId == null) {
            return;
        }

        // Check if any auths exist for that config
        boolean hasAuths;
        try (var ps = conn.prepareStatement(
                "SELECT COUNT(*) FROM resource_type_auth WHERE resource_type_config_id = ?")) {
            ps.setLong(1, dockerRepoConfigId);
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                hasAuths = rs.getLong(1) > 0;
            }
        }
        if (!hasAuths) {
            return;
        }

        // Ensure a DOCKER_REPOSITORY discovery_service_config row exists
        Long discoveryConfigId = null;
        try (var ps = conn.prepareStatement(
                "SELECT id FROM discovery_service_config WHERE type_name = 'DOCKER_REPOSITORY'");
             ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                discoveryConfigId = rs.getLong(1);
            }
        }
        if (discoveryConfigId == null) {
            // Get interval from old config
            int interval = 60;
            int parallelism = 1;
            try (var ps = conn.prepareStatement(
                    "SELECT check_interval_minutes, parallelism FROM resource_type_config WHERE id = ?")) {
                ps.setLong(1, dockerRepoConfigId);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        interval = rs.getInt(1);
                        parallelism = rs.getInt(2);
                    }
                }
            }
            try (var ps = conn.prepareStatement(
                    "INSERT INTO discovery_service_config (type_name, sync_interval_minutes, parallelism) VALUES (?, ?, ?)")) {
                ps.setString(1, "DOCKER_REPOSITORY");
                ps.setInt(2, interval);
                ps.setInt(3, parallelism);
                ps.executeUpdate();
            }
            try (var ps = conn.prepareStatement(
                    "SELECT id FROM discovery_service_config WHERE type_name = 'DOCKER_REPOSITORY'");
                 ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    discoveryConfigId = rs.getLong(1);
                }
            }
        }

        if (discoveryConfigId == null) {
            return;
        }

        // Migrate auth rows
        final long finalDiscoveryConfigId = discoveryConfigId;
        try (var selectPs = conn.prepareStatement(
                "SELECT name, auth_type, url_pattern, username, password FROM resource_type_auth WHERE resource_type_config_id = ?")) {
            selectPs.setLong(1, dockerRepoConfigId);
            try (ResultSet rs = selectPs.executeQuery()) {
                while (rs.next()) {
                    try (var insertPs = conn.prepareStatement(
                            "INSERT INTO discovery_service_auth (discovery_service_config_id, name, auth_type, url_pattern, username, password) VALUES (?, ?, ?, ?, ?, ?)")) {
                        insertPs.setLong(1, finalDiscoveryConfigId);
                        insertPs.setString(2, rs.getString("name"));
                        insertPs.setString(3, rs.getString("auth_type"));
                        insertPs.setString(4, rs.getString("url_pattern"));
                        insertPs.setString(5, rs.getString("username"));
                        insertPs.setString(6, rs.getString("password"));
                        insertPs.executeUpdate();
                    }
                }
            }
        }
    }

    private boolean tableExists(Connection conn, String tableName) throws Exception {
        DatabaseMetaData metaData = conn.getMetaData();
        try (ResultSet rs = metaData.getTables(null, null, tableName.toUpperCase(), null)) {
            if (rs.next()) return true;
        }
        try (ResultSet rs = metaData.getTables(null, null, tableName.toLowerCase(), null)) {
            return rs.next();
        }
    }
}
