CREATE TABLE IF NOT EXISTS notification_provider (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(255) NOT NULL,
    type                 VARCHAR(32)  NOT NULL,
    smtp_host            VARCHAR(255),
    smtp_port            INTEGER,
    smtp_username        VARCHAR(255),
    smtp_password        VARCHAR(255),
    smtp_use_tls         BOOLEAN DEFAULT TRUE,
    sender_email         VARCHAR(255),
    recipient_email      VARCHAR(255),
    webhook_url          VARCHAR(2048),
    webhook_body_template TEXT,
    discord_webhook_url  VARCHAR(2048)
);
