CREATE TABLE IF NOT EXISTS notification_policy (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(255) NOT NULL,
    provider_id               BIGINT NOT NULL REFERENCES notification_provider(id),
    notify_on_outage_started  BOOLEAN NOT NULL DEFAULT FALSE,
    notify_on_outage_ended    BOOLEAN NOT NULL DEFAULT FALSE,
    scope_type                VARCHAR(16) NOT NULL DEFAULT 'ALL'
);

CREATE TABLE IF NOT EXISTS notification_policy_group (
    policy_id BIGINT NOT NULL REFERENCES notification_policy(id) ON DELETE CASCADE,
    group_id  BIGINT NOT NULL,
    PRIMARY KEY (policy_id, group_id)
);

CREATE TABLE IF NOT EXISTS notification_policy_resource (
    policy_id   BIGINT NOT NULL REFERENCES notification_policy(id) ON DELETE CASCADE,
    resource_id BIGINT NOT NULL,
    PRIMARY KEY (policy_id, resource_id)
);
