ALTER TABLE notification_provider ADD COLUMN IF NOT EXISTS gitlab_base_url   VARCHAR(2048);
ALTER TABLE notification_provider ADD COLUMN IF NOT EXISTS gitlab_project_id VARCHAR(255);
ALTER TABLE notification_provider ADD COLUMN IF NOT EXISTS gitlab_token       VARCHAR(255);

CREATE TABLE IF NOT EXISTS outage_notification_ref (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outage_id    BIGINT NOT NULL,
    provider_id  BIGINT NOT NULL,
    external_ref VARCHAR(64) NOT NULL
);
