CREATE TABLE IF NOT EXISTS resource_type_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(255),
    check_interval_minutes INT DEFAULT 5 NOT NULL,
    parallelism INT DEFAULT 2 NOT NULL,
    allow_public_add BOOLEAN DEFAULT FALSE NOT NULL,
    allow_public_check_now BOOLEAN DEFAULT FALSE NOT NULL,
    outage_threshold INT DEFAULT 3 NOT NULL,
    recovery_threshold INT DEFAULT 2 NOT NULL
);

ALTER TABLE IF EXISTS resource_type_config ADD COLUMN IF NOT EXISTS outage_threshold INT DEFAULT 3 NOT NULL;
ALTER TABLE IF EXISTS resource_type_config ADD COLUMN IF NOT EXISTS recovery_threshold INT DEFAULT 2 NOT NULL;

CREATE TABLE IF NOT EXISTS monitored_resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS outage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (resource_id) REFERENCES monitored_resource(id)
);
