ALTER TABLE resource_type_config ADD COLUMN IF NOT EXISTS outage_threshold INT DEFAULT 3 NOT NULL;
ALTER TABLE resource_type_config ADD COLUMN IF NOT EXISTS recovery_threshold INT DEFAULT 2 NOT NULL;

CREATE TABLE IF NOT EXISTS outage (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT NOT NULL,
    start_date  TIMESTAMP NOT NULL,
    end_date    TIMESTAMP,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (resource_id) REFERENCES monitored_resource(id)
);
